name = "security-headers-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "security-headers-worker"
route = "1page.tools/*"

[env.staging]
name = "security-headers-worker-staging"
